var $$=Dom7;var currentUser=null;var justReadIndex=null;var isCommentToPost=true;var targetPostId=null;var targetCommentId=null;var targetUserId=null;var targetUsername=null;var ut=null;var device_token=null;var commentList=[];var userPostList=[];var currentIndex=1;var userCurrentIndex=1;var newCurrentIndex=1;var userLoading=false;var guestSwiper=null;var workingList=[];var notificationList=[];var postList=[];var browserList=[];var newPostList=[];var picProportion=1;var mainPostPageTab="new";
var fileURL="";var homeLoading=false;var userPageLoading=false;var udid="";$("link[href='css/my-app.css']").remove();var popupHTML="";popupHTML+='    <div class="popup popup-post-text">';popupHTML+='      <div class="popup-navbar navbar title-bar row" >';popupHTML+='          <div class="col-33 left" onclick = "myApp.closeModal(\'.popup-post-text\')">';popupHTML+='            <a class="link " >';popupHTML+="              \u53d6\u6d88";popupHTML+="            </a>                   ";popupHTML+="          </div>";
popupHTML+='          <div class=" center ">';popupHTML+="          </div>";popupHTML+='          <div class="col-33 right" onclick = "postText()">';popupHTML+='            <a class="link " >';popupHTML+="              \u53d1\u5e03";popupHTML+="            </a>               ";popupHTML+="          </div>                            ";popupHTML+="      </div>";popupHTML+='      <div class="list-block" id="post-image-panel-1">';popupHTML+="        <ul>";popupHTML+="          \x3c!-- Text inputs --\x3e";
popupHTML+="          <li>";popupHTML+='            <div class="item-content">';popupHTML+='              \x3c!-- <div class="item-media" "><img id="post-image-preview" width="66" style="border:1px solid #EEE"></div>           --\x3e';popupHTML+='              <div class="item-inner no-bottom-line">';popupHTML+='                <div class="item-input">';popupHTML+='                  <textarea id = "post-text-input" type="text" placeholder="\u8bf4\u4e9b\u4ec0\u4e48\u5462..."></textarea>';
popupHTML+="                </div>";popupHTML+="              </div>";popupHTML+="            </div>";popupHTML+="          </li>";popupHTML+="       </ul>";popupHTML+="      </div>";popupHTML+="    </div>    ";popupHTML+='    <div class="popup popup-post-image">';popupHTML+='      <div class="popup-navbar navbar title-bar row" >';popupHTML+='          <div class="col-33 left" onclick = "myApp.closeModal(\'.popup-post-image\')">';popupHTML+='            <a class="link " >';popupHTML+="              \u53d6\u6d88";
popupHTML+="            </a>                   ";popupHTML+="          </div>";popupHTML+='          <div class=" center ">';popupHTML+="          </div>";popupHTML+='          <div class="col-33 right" onclick = "postPicture()">';popupHTML+='            <a class="link " >';popupHTML+="              \u53d1\u5e03";popupHTML+="            </a>               ";popupHTML+="          </div>                            ";popupHTML+="      </div>";popupHTML+='      <div class="list-block" id="post-image-panel-1">';
popupHTML+="        <ul>";popupHTML+="          \x3c!-- Text inputs --\x3e";popupHTML+="          <li>";popupHTML+='            <div class="item-content">';popupHTML+='              \x3c!-- <div class="item-media" onclick = "photoShoot ()"><img id="post-image-preview" width="66" style="border:1px solid #EEE"></div>           --\x3e';popupHTML+='              <div class="item-inner no-bottom-line">';popupHTML+='                <div class="item-input">';popupHTML+='                  <textarea id = "post-image-title-input" type="text" placeholder="\u6807\u9898"></textarea>';
popupHTML+="                </div>";popupHTML+="              </div>";popupHTML+="            </div>";popupHTML+="          </li>";popupHTML+="          <li>";popupHTML+='            <div class="item-content">';popupHTML+='              <div class="item-media" onclick="photoShoot(\'album\')"><img id="post-image-preview" width="88" style="border:1px solid #EEE"></div>          ';popupHTML+='              <div class="item-inner">';popupHTML+='                <div class="item-input">';popupHTML+="                </div>";
popupHTML+="              </div>";popupHTML+="            </div>";popupHTML+="          </li> ";popupHTML+="       </ul>";popupHTML+="      </div>";popupHTML+='      <div class="list-block" id="post-image-panel-2">';popupHTML+="        <ul>";popupHTML+='          <li class="item-content"  onclick="photoShoot(\'album\')">';popupHTML+='            <div class="item-media"><i style="color:#AAA;" class="fa fa-camera"></i></div>';popupHTML+='            <div class="item-inner">';popupHTML+='              <div class="item-title" style="color:#222;">\u91cd\u65b0\u9009\u62e9\u56fe\u7247</div>';
popupHTML+='              <div class="item-after"></div>';popupHTML+="            </div>";popupHTML+="          </li>";popupHTML+="       </ul>";popupHTML+="      </div>           ";popupHTML+="    </div>    ";popupHTML+='    <div class="popup popup-post">';popupHTML+='      <div class="popup-navbar navbar title-bar row" >';popupHTML+='          <div class="col-33 left" onclick = "addPostPopupClose()">';popupHTML+='            <a class="link " >';popupHTML+="              \u53d6\u6d88";
popupHTML+="            </a>                   ";popupHTML+="          </div>";popupHTML+='          <div class=" center ">';popupHTML+="            \x3c!-- <span >\u53d1\u4e2a\u516d\u513f</span> --\x3e";popupHTML+="          </div>";popupHTML+='          <div class="col-33 right" onclick = "postLink()">';popupHTML+='            <a class="link " >';popupHTML+="              \u53d1\u5e03";popupHTML+="            </a>               ";popupHTML+="          </div>                            ";
popupHTML+="      </div>";popupHTML+='      <div class="list-block" id="post-panel-1">';popupHTML+="        <ul>";popupHTML+="          \x3c!-- Text inputs --\x3e";popupHTML+="          <li>";popupHTML+='            <div class="item-content">';popupHTML+='              <div class="item-inner">';popupHTML+='                \x3c!-- <div class="item-title label">\u7f51\u5740 URL</div> --\x3e';popupHTML+='                <div class="item-input">';popupHTML+='                  <input id = "post-address-input" type="text" placeholder="\u7f51\u5740 URL">';
popupHTML+="                </div>";popupHTML+="              </div>";popupHTML+="            </div>";popupHTML+="          </li>";popupHTML+="          <li>";popupHTML+='            <div class="item-content">';popupHTML+='              <div class="item-inner">';popupHTML+='                \x3c!-- <div class="item-title label">\u6807\u9898</div> --\x3e';popupHTML+='                <div class="item-input">';popupHTML+='                  <textarea id = "post-title-input" type="text" placeholder="\u6807\u9898"></textarea>';
popupHTML+="                </div>";popupHTML+="              </div>";popupHTML+="            </div>";popupHTML+="          </li>";popupHTML+="       </ul>";popupHTML+="      </div>";popupHTML+='      <div class="list-block" id="post-panel-2">';popupHTML+="        <ul>";popupHTML+='          <li class="item-content"  onclick = "pastFromClipBoard()">';popupHTML+='            <div class="item-media"><i style="color:#AAA;" class="fa fa-copy"></i></div>';popupHTML+='            <div class="item-inner">';
popupHTML+='              <div class="item-title" style="color:#222;">\u4ece\u7c98\u8d34\u677f\u83b7\u53d6\u5730\u5740</div>';popupHTML+='              <div class="item-after"></div>';popupHTML+="            </div>";popupHTML+="          </li>";popupHTML+='          <li class="item-content"  onclick="getUrlTitle()">';popupHTML+='            <div class="item-media"><i style="color:#AAA;" class="fa fa-at"></i></div>';popupHTML+='            <div class="item-inner">';popupHTML+='              <div class="item-title" style="color:#222;">\u667a\u80fd\u8bfb\u53d6\u7f51\u9875\u6807\u9898</div>';
popupHTML+='              <div class="item-after"></div>';popupHTML+="            </div>";popupHTML+="          </li>";popupHTML+="       </ul>";popupHTML+="      </div>           ";popupHTML+="    </div>";popupHTML+='    <div class="popup popup-inbox">   ';popupHTML+="    </div>";popupHTML+='    <div class="popup popup-config">';popupHTML+='      <div class="popup-navbar navbar title-bar row" >';popupHTML+='        \x3c!-- <div class="row"> --\x3e';popupHTML+='          \x3c!-- <div class="col-33 left" > --\x3e';
popupHTML+='            <a class="col-33 left link " onclick = "configPopupClose()">';popupHTML+='              <i class="fa fa-chevron-left"></i>';popupHTML+="            </a>                   ";popupHTML+="          \x3c!-- </div> --\x3e";popupHTML+='          <div class="center ">';popupHTML+="            <span >\u8bbe\u7f6e</span>";popupHTML+="          </div>";popupHTML+='          <div class="col-33 right" >';popupHTML+='            \x3c!-- <a class="link">\u4fdd\u5b58</a> --\x3e';
popupHTML+="          </div>                            ";popupHTML+="      </div>";popupHTML+='      <div class="list-block">';popupHTML+="        <ul>";popupHTML+="          <li>";popupHTML+='            <div class="item-content">';popupHTML+='              <div class="item-inner">';popupHTML+='                <div class="item-title label">nickname</div>';popupHTML+='                <div class="item-input">';popupHTML+='                  <input id = "setting-nickname-input" type="text" placeholder="nickname">';
popupHTML+="                </div>";popupHTML+="              </div>";popupHTML+="            </div>";popupHTML+="          </li>";popupHTML+="       </ul>";popupHTML+="      </div>  ";popupHTML+='      <div class="content-block">';popupHTML+="      </div>";popupHTML+='      <div class="list-block">';popupHTML+="        <ul>";popupHTML+="          \x3c!-- Text inputs --\x3e";popupHTML+="          <li>";popupHTML+='            <div class="item-content" onclick="logOut()">';popupHTML+='              <div class="item-inner">';
popupHTML+='                  <a style="color:rgba(252,221,29,1)">';popupHTML+="                    Log Out ";popupHTML+="                  </a>";popupHTML+="              </div>";popupHTML+="            </div>";popupHTML+="          </li>";popupHTML+="       </ul>";popupHTML+="      </div>           ";popupHTML+="    </div>";popupHTML+='    <div class="popup popup-tutorial">';popupHTML+='      <div class="swiper-container">';popupHTML+='        <div class="swiper-wrapper">';popupHTML+='          <div class="swiper-slide"><img class="screen-shot" src="./img/screenshot/5.5-inch (iPhone 6+) - Screenshot 1.jpg"></div>';
popupHTML+='          <div class="swiper-slide"><img class="screen-shot" src="./img/screenshot/5.5-inch (iPhone 6+) - Screenshot 2.jpg"></div>';popupHTML+='          <div class="swiper-slide" onload="console.log(1)"><img class="screen-shot" src="./img/screenshot/5.5-inch (iPhone 6+) - Screenshot 3.jpg"><div onclick="loginPopupOpen()" style="display:none"id="tutorial-button"class="button button-fill bg-meiliuer-yellow tutorial-button button-big ">\u8fdb\u5165\u6ca1\u516d\u513f</div>';popupHTML+="          </div>";
popupHTML+='        \x3c!-- <div class="swiper-pagination"></div> --\x3e';popupHTML+="        </div>";popupHTML+="      </div>";popupHTML+="    </div>";popupHTML+='    <div class="popup popup-login">';popupHTML+='      <div class="page-content" id="popup-login-content">';popupHTML+='        <div class="content-block">';popupHTML+='          <img class="login-page-logo" src="img/half_trans_solid.png" >';popupHTML+='          <div class="login-page-slogan">';popupHTML+="            \u53d1\u73b0\u4e00\u4e2a\u66f4\u5e7f\u9614\u7684\u4e16\u754c";
popupHTML+="          </div>";popupHTML+="          \x3c!-- Buttons row as tabs controller --\x3e";popupHTML+="        </div>";popupHTML+="        \x3c!-- Tabs, tabs wrapper --\x3e";popupHTML+='        <div id="login-signup-tab" class="tabs ">';popupHTML+="          \x3c!-- Tab 1, active by default --\x3e";popupHTML+='          <div id="login-tab" class="tab ">';popupHTML+='            <div class="content-block">';popupHTML+='              <div class="list-block">';popupHTML+="                <ul>";
popupHTML+="                  <li>";popupHTML+='                    <div class="item-content">';popupHTML+='                      <div class="item-inner">';popupHTML+='                        <div class="item-title label">\u90ae\u7bb1\u6216\u7528\u6237\u540d</div>';popupHTML+='                        <div class="item-input">';popupHTML+='                          <input  class= "login-signup-input" id = "post-email-input" type="email" placeholder="\u8fd9\u5c06\u662f\u60a8\u53d6\u56de\u5bc6\u7801\u7528\u7684\u90ae\u7bb1">';
popupHTML+="                        </div>";popupHTML+="                      </div>";popupHTML+="                    </div>";popupHTML+="                  </li>";popupHTML+="                  <li>";popupHTML+='                    <div class="item-content">';popupHTML+='                      <div class="item-inner">';popupHTML+='                        <div class="item-title label">\u5bc6\u7801</div>';popupHTML+='                        <div class="item-input">';popupHTML+='                          <input  class= "login-signup-input" id = "post-password-input" type="password" placeholder="\u5bc6\u7801">';
popupHTML+="                        </div>";popupHTML+="                      </div>";popupHTML+="                    </div>";popupHTML+="                  </li>          ";popupHTML+="               </ul>";popupHTML+="              </div>  ";popupHTML+='              <div class="content-block">';popupHTML+="              </div>";popupHTML+='              <div class="row">';popupHTML+='                <div class="col-100">';popupHTML+='                  <div onclick="logIn()"  class="button button-fill button-big  bg-meiliuer-yellow color-black meiliuer-big-fill-button ">      ';
popupHTML+="                          \u767b\u5f55";popupHTML+="                  </div>                     ";popupHTML+="                </div>";popupHTML+='                <div class="col-50">';popupHTML+='                  <div class="forget-password-text" onclick="">';popupHTML+='                    <a href="#signup-tab" style="float:left;color:#6d6d72!important;" class="tab-link active ">\u6ce8\u518c\u8d26\u53f7</a>                      ';popupHTML+="                  </div>";popupHTML+="                </div>              ";
popupHTML+='                <div class="col-50" >';popupHTML+='                  <div class="forget-password-text" style="float:right;"  onclick="forgetPassword()" >      ';popupHTML+="                          \u5fd8\u8bb0\u5bc6\u7801";popupHTML+="                  </div>                        ";popupHTML+="                </div>";popupHTML+="";popupHTML+="              </div>";popupHTML+="            </div>";popupHTML+="          </div>";popupHTML+="          \x3c!-- Tab 2 --\x3e";popupHTML+='          <div id="signup-tab" class="tab active">';
popupHTML+='            <div class="content-block">';popupHTML+='              <div class="list-block">';popupHTML+="                <ul>";popupHTML+="                  <li>";popupHTML+='                    <div class="item-content">';popupHTML+='                      <div class="item-inner">';popupHTML+='                        <div class="item-title label">\u7528\u6237\u540d</div>';popupHTML+='                        <div class="item-input">';popupHTML+='                          <input class= "login-signup-input" id = "signup-username-input" type="text" placeholder="\u60a8\u7559\u8a00\u65f6\u522b\u4eba\u770b\u5230\u7684\u7528\u6237id">';
popupHTML+="                        </div>";popupHTML+="                      </div>";popupHTML+="                    </div>";popupHTML+="                  </li>                  ";popupHTML+="                  <li>";popupHTML+='                    <div class="item-content">';popupHTML+='                      <div class="item-inner">';popupHTML+='                        <div class="item-title label">\u90ae\u7bb1</div>';popupHTML+='                        <div class="item-input">';popupHTML+='                          <input  class= "login-signup-input" id = "signup-email-input" type="email" placeholder="\u60a8\u53d6\u56de\u5bc6\u7801\u7528\u7684\u90ae\u7bb1">';
popupHTML+="                        </div>";popupHTML+="                      </div>";popupHTML+="                    </div>";popupHTML+="                  </li>";popupHTML+="                  <li>";popupHTML+='                    <div class="item-content">';popupHTML+='                      <div class="item-inner">';popupHTML+='                        <div class="item-title label">\u5bc6\u7801</div>';popupHTML+='                        <div class="item-input">';popupHTML+='                          <input  class= "login-signup-input" id = "signup-password-input" type="password" placeholder="\u5bc6\u7801">';
popupHTML+="                        </div>";popupHTML+="                      </div>";popupHTML+="                    </div>";popupHTML+="                  </li>          ";popupHTML+="               </ul>";popupHTML+="              </div>  ";popupHTML+='              <div class="content-block">';popupHTML+="              </div>";popupHTML+='              <div class="row">';popupHTML+='                <div class="col-100">';popupHTML+='                  <div onclick="signUp()" class="button button-fill button-big  bg-meiliuer-yellow color-black meiliuer-big-fill-button ">      ';
popupHTML+="                      \u6ce8\u518c";popupHTML+="                  </div> ";popupHTML+='                  <div class="col-100">';popupHTML+='                    <div class="forget-password-text" onclick="">';popupHTML+='                      <a href="#login-tab" class="tab-link forget-password-text active">\u5df2\u6709\u8d26\u53f7\uff1f\u70b9\u51fb\u767b\u5f55</a>                    ';popupHTML+="                    </div>";popupHTML+="                  </div>                                    ";
popupHTML+="                </div>";popupHTML+="              </div>";popupHTML+="            </div>";popupHTML+="          </div>";popupHTML+="        </div>";popupHTML+='        <img class="login-background" src= "img/login_background.png">';popupHTML+="      </div>          ";popupHTML+="    </div>    ";var viewHTML="";viewHTML+='    <div class="views">';viewHTML+='      \x3c!-- <div class="statusbar-overlay panel-color"></div> --\x3e';viewHTML+='      \x3c!-- Your main view, should have "view-main" class--\x3e';
viewHTML+='      <div class="view view-main">';viewHTML+="";viewHTML+="        \x3c!-- Top Navbar--\x3e";viewHTML+='        <div class="navbar">';viewHTML+='          <div class="navbar-inner row" data-page="index" id="index-navbar">';viewHTML+='            <div class="left col-33"> ';viewHTML+='<span id="carma-number"  onclick="carmaPopover()"></span>';viewHTML+="            </div>";viewHTML+='            <div class="center sliding " >';viewHTML+='              <img id="index-navbar-logo" class="navbar-logo" src="img/half_trans_solid.png">';
viewHTML+="            </div>";viewHTML+='            <div class=" right col-33" >';viewHTML+='              <a class=" login-only link"  style="width:100%" onclick="addNewPost ()">';viewHTML+='                <i class="fa fa-pencil-square-o icon ">';viewHTML+='                  <span class="badge bg-red"  style="display:none"></span>';viewHTML+="                </i>";viewHTML+="              </a>                 ";viewHTML+="            </div>";viewHTML+='    <div class="subnavbar"> ';
viewHTML+="        \x3c!-- Sub navbar content, for example tabs buttons --\x3e ";viewHTML+='        <div class="buttons-row " > ';viewHTML+='            <a id="new-feed-tab-button" href = "#new-feed-tab" class="button tab-link active">\u4eca\u65e5\u6700\u4f73</a> ';viewHTML+='            <a id="hot-feed-tab-button"  href="#hot-feed-tab" class="button  tab-link ">\u672c\u5468\u6700\u70ed</a> ';viewHTML+="        </div> ";viewHTML+="    </div> ";viewHTML+="          </div>";viewHTML+='          <div class="navbar-inner row cached" data-page="viewPage">';
viewHTML+='            <div class="col-33 left back" onclick="mainView.router.back()">';viewHTML+='                <i class="fa fa-chevron-left"></i>';viewHTML+="            </div>     ";viewHTML+='            <div class="center sliding " >';viewHTML+='              <img id="index-navbar-logo" class="navbar-logo" src="img/half_trans_solid.png">';viewHTML+="            </div>";viewHTML+='            <div class=" right col-33" >';viewHTML+="               ";viewHTML+="            </div>";
viewHTML+="          </div>          ";viewHTML+='          <div class="navbar-inner row cached" data-page="user" id="user-navbar">';viewHTML+='            <div class="col-33 left back" onclick="mainView.router.back()">';viewHTML+='                <i class="fa fa-chevron-left"></i>';viewHTML+="            </div>            ";viewHTML+='            <div id="user-page-nav-title" class="center sliding">';viewHTML+="              ";viewHTML+="            </div>";viewHTML+='            <div class="col-33 right" id="logout-placeholder">';
viewHTML+="";viewHTML+="            </div>";viewHTML+='            <div class="subnavbar">';viewHTML+="                \x3c!-- Sub navbar content, for example tabs buttons --\x3e";viewHTML+='                <div class="row">';viewHTML+='                  <div class="col-33" >';viewHTML+='                    <div class="number" id="number-of-posts">13</div>';viewHTML+='                    <div class="description">\u53d1\u5e16\u6570</div>';viewHTML+="                  </div>";viewHTML+='                  <div class="col-33">';
viewHTML+='                    <div class="number" id="number-of-likes-sent">271</div>';viewHTML+='                    <div class="description">\u8d5e\u8fc7</div>';viewHTML+="                  </div>";viewHTML+='                  <div class="col-33" >';viewHTML+='                    <div class="number" id="number-of-likes-received">36</div>';viewHTML+='                    <div class="description">\u88ab\u8d5e\u8fc7</div>';viewHTML+="                  </div>";viewHTML+="                </div>";
viewHTML+="            </div>                        ";viewHTML+="          </div>    ";viewHTML+='          <div class="navbar-inner row cached" data-page="inbox">';viewHTML+='              <div class="col-33 left back" onclick = "inboxPopupClose()">';viewHTML+='                <a href="#" class="link " >';viewHTML+='                  <i class="fa fa-chevron-left"></i>';viewHTML+="                </a>                   ";viewHTML+="              </div>";viewHTML+='              <div class="center ">';
viewHTML+="                <span >\u4fe1\u7bb1</span>";viewHTML+="              </div>";viewHTML+='              <div class="col-33 right">';viewHTML+="              </div>                            ";viewHTML+="          </div>                 ";viewHTML+='          <div class="navbar-inner row cached" data-page="post">';viewHTML+='            \x3c!-- <div class="row"> --\x3e';viewHTML+='              <div class="col-33 left back" onclick="mainView.router.back()">';viewHTML+='                <i class="fa fa-chevron-left"></i>';
viewHTML+="              </div>";viewHTML+='              <div class=" center slide">';viewHTML+="                \u8bc4\u8bba";viewHTML+="              </div>              ";viewHTML+='              <div class="col-33 right">               ';viewHTML+="              </div>";viewHTML+="          </div>          ";viewHTML+="        </div>";viewHTML+="        \x3c!-- Pages, because we need fixed-through navbar and toolbar, it has additional appropriate classes--\x3e";viewHTML+='        <div class="pages navbar-through toolbar-through">';
viewHTML+="          \x3c!-- Page, data-page contains page name--\x3e";viewHTML+='          <div id="post-page" data-page="post" class="page cached">';viewHTML+='            <div class="page-content" id="post-page-page-content">';viewHTML+='              <img onclick="openElem(0)" class="post-image" onerror="this.onerror = null; this.src= \'http://meiliuer.com/images/temp.jpg\' " src="http://meiliuer.com/uploads/posts/176381/pic_1448388602.jpg">              ';viewHTML+='              <div class="post-unit-textblock">                ';
viewHTML+='                <div class="post-title" onclick="openElem(0)">';viewHTML+="                  Musk and Jeff \u7684\u6495\u903c\u6218";viewHTML+="                </div>";viewHTML+='                <div class="post-author">';viewHTML+='                  <img class="post-author-image" src="http://meiliuer.com/uploads/avatars/176381/GTR.jpg">';viewHTML+='                  <span class="post-author-text">Terry</span>';viewHTML+="                </div>";viewHTML+='                <div class="post-address">';
viewHTML+="                  http://www.marketwatch.com/story/jeff-bezoss-first-day-on-twitter-already-involves-a-twitter-fight-2015-11-24?link=sfmw_fb";viewHTML+="                </div>      ";viewHTML+="              </div>";viewHTML+='              <div class="list-block" id="comment-list">';viewHTML+="                <ul>";viewHTML+="                  <li>";viewHTML+='                    <a href="#" class="item-link item-content">';viewHTML+='                      <div class="item-media"><i class="icon icon-f7"></i></div>';
viewHTML+='                      <div class="item-inner">';viewHTML+='                        <div class="item-title">Item title</div>';viewHTML+='                        <div class="item-after">Label</div>';viewHTML+="                      </div>";viewHTML+="                    </a>";viewHTML+="                  </li>";viewHTML+="                </ul>              ";viewHTML+="              </div>";viewHTML+="";viewHTML+="            </div>";viewHTML+="          </div>";viewHTML+='          <div id="viewPage-page" data-page="viewPage" class="page cached">';
viewHTML+="            \x3c!-- Scrollable page content--\x3e";viewHTML+='            <div class="page-content">';viewHTML+='              <img id="view-image-tag" >   ';viewHTML+="            </div>                     ";viewHTML+="          </div>          ";viewHTML+='          <div id="home-page" data-page="index" class="page with-subnavbar">';viewHTML+="            \x3c!-- Scrollable page content--\x3e";viewHTML+='            <div class="page-content pull-to-refresh-content  infinite-scroll " data-ptr-distance="75">';
viewHTML+='<div class="tabs-swipeable-wrap ">';viewHTML+='\t\t\t <div class="tabs">';viewHTML+=' \t\t\t\t<div class="tab active" id="new-feed-tab">';viewHTML+='              <div class="pull-to-refresh-layer ">';viewHTML+='                <div class="preloader"></div>';viewHTML+='                <div class="pull-to-refresh-arrow"></div>';viewHTML+="              </div>              ";viewHTML+='              <div class="list-block " id="new-post-list">';viewHTML+='                <div class="row">';
viewHTML+='                  <div class="col-100" style="text-align:center; padding-top:20px;">';viewHTML+='                    <div class=" preloader"></div>';viewHTML+="                  </div>                  ";viewHTML+="                </div>                ";viewHTML+="              </div>";viewHTML+="                \x3c!-- Preloader --\x3e";viewHTML+='              <div class="infinite-scroll-preloader">';viewHTML+='                <div class="preloader"></div>';viewHTML+="              </div>";
viewHTML+="            </div> ";viewHTML+=' \t\t\t\t<div class="tab" id="hot-feed-tab">';viewHTML+='              <div class="pull-to-refresh-layer ">';viewHTML+='                <div class="preloader"></div>';viewHTML+='                <div class="pull-to-refresh-arrow"></div>';viewHTML+="              </div>              ";viewHTML+='              <div class="list-block " id="post-list">';viewHTML+='                <div class="row">';viewHTML+='                  <div class="col-100" style="text-align:center; padding-top:20px;">';
viewHTML+='                    <div class=" preloader"></div>';viewHTML+="                  </div>                  ";viewHTML+="                </div>                ";viewHTML+="              </div>";viewHTML+="                \x3c!-- Preloader --\x3e";viewHTML+='              <div class="infinite-scroll-preloader">';viewHTML+='                <div class="preloader"></div>';viewHTML+="              </div>";viewHTML+=" \t\t\t\t</div>";viewHTML+=" \t\t\t</div>";viewHTML+="</div>";viewHTML+="          </div>";
viewHTML+='<div class="toolbar tabbar tabbar-labels"> ';viewHTML+='    <div class="toolbar-inner"> ';viewHTML+='        <a href="#tab1" class="tab-link active" onclick="getHomePage ()"> ';viewHTML+='            <i class="ion-ios-home"></i> ';viewHTML+='            <span class="tabbar-label">\u4e3b\u9875</span> ';viewHTML+="        </a> ";viewHTML+='        <a href="#tab4" class="tab-link" onclick="inboxPopupOpen ()"> ';viewHTML+='            <i class="ion-ios-email-outline"><span class="badge bg-red" id="unread-badge" style="display:none; margin-left: -7px;"></span></i> ';
viewHTML+="                  ";viewHTML+='            <span class="tabbar-label">\u6d88\u606f</span> ';viewHTML+="        </a> ";viewHTML+='        <a href="#tab5" class="tab-link" onclick="selfPage()"> ';viewHTML+='            <i class="ion-ios-person-outline"></i> ';viewHTML+='            <span class="tabbar-label">\u5173\u4e8e\u6211</span> ';viewHTML+="        </a> ";viewHTML+="    </div> ";viewHTML+="</div> ";viewHTML+=" \t\t\t</div>";viewHTML+='          <div id="inbox-page" data-page="inbox" class="page cached">';
viewHTML+='            <div class="page-content">';viewHTML+='              <div class="list-block media-list" id="notification-list">';viewHTML+="                <ul>";viewHTML+="                </ul>";viewHTML+="              </div>               ";viewHTML+="            </div>";viewHTML+='<div class="toolbar tabbar tabbar-labels"> ';viewHTML+='    <div class="toolbar-inner"> ';viewHTML+='        <a href="#tab1" class="tab-link" onclick="getHomePage ()"> ';viewHTML+='            <i class="ion-ios-home-outline"></i> ';
viewHTML+='            <span class="tabbar-label">\u4e3b\u9875</span> ';viewHTML+="        </a> ";viewHTML+='        <a href="#tab4" class="tab-link active" onclick="inboxPopupOpen ()"> ';viewHTML+='            <i class="ion-ios-email"><span class="badge bg-red" id="unread-badge" style="display:none; margin-left: -7px;"></span></i> ';viewHTML+="                  ";viewHTML+='            <span class="tabbar-label">\u6d88\u606f</span> ';viewHTML+="        </a> ";viewHTML+='        <a href="#tab5" class="tab-link" onclick="selfPage()"> ';
viewHTML+='            <i class="ion-ios-person-outline"></i> ';viewHTML+='            <span class="tabbar-label">\u5173\u4e8e\u6211</span> ';viewHTML+="        </a> ";viewHTML+="    </div> ";viewHTML+="</div> ";viewHTML+="          </div>";viewHTML+='          <div id="user-page" data-page="user" class="page cached">';viewHTML+="            \x3c!-- Scrollable page content--\x3e";viewHTML+='            <div class="page-content pull-to-refresh-content infinite-scroll " >';viewHTML+='              \x3c!-- <div class="content-block-title">Welcome To My Awesome App</div> --\x3e';
viewHTML+='              <div class="pull-to-refresh-layer ">';viewHTML+='                <div class="preloader"></div>';viewHTML+='                <div class="pull-to-refresh-arrow"></div>';viewHTML+="              </div>              ";viewHTML+='              <div class="list-block " id="user-post-list">';viewHTML+="                <ul>                                                                       ";viewHTML+="                </ul>";viewHTML+="              </div>";viewHTML+="                \x3c!-- Preloader --\x3e";
viewHTML+='              <div class="infinite-scroll-preloader">';viewHTML+='                <div class="preloader"></div>';viewHTML+="              </div>";viewHTML+="            </div>                   ";viewHTML+='<div class="toolbar tabbar tabbar-labels"> ';viewHTML+='    <div class="toolbar-inner"> ';viewHTML+='        <a href="#tab1" class="tab-link " onclick="getHomePage ()"> ';viewHTML+='            <i class="ion-ios-home-outline"></i> ';viewHTML+='            <span class="tabbar-label">\u4e3b\u9875</span> ';
viewHTML+="        </a> ";viewHTML+='        <a href="#tab4" class="tab-link" onclick="inboxPopupOpen ()"> ';viewHTML+='            <i class="ion-ios-email-outline"><span class="badge bg-red" id="unread-badge" style="display:none; margin-left: -7px;"></span></i> ';viewHTML+="                  ";viewHTML+='            <span class="tabbar-label">\u6d88\u606f</span> ';viewHTML+="        </a> ";viewHTML+='        <a href="#tab5" class="tab-link active " onclick="selfPage()"> ';viewHTML+='            <i class="ion-ios-person"></i> ';
viewHTML+='            <span class="tabbar-label">\u5173\u4e8e\u6211</span> ';viewHTML+="        </a> ";viewHTML+="    </div> ";viewHTML+="</div> ";viewHTML+="          </div>          ";viewHTML+="        </div>";viewHTML+="        \x3c!-- Bottom Toolbar--\x3e";viewHTML+="      </div>";viewHTML+="";viewHTML+="    </div>";var panelHTML="";panelHTML+='    <div class="panel-overlay"></div>';panelHTML+="    \x3c!-- Left panel with reveal effect--\x3e";panelHTML+='    <div class="panel panel-left panel-reveal panel-color">';
panelHTML+='      \x3c!-- <div class="statusbar-overlay panel-color"></div> --\x3e';panelHTML+='      <div class="content-block">';panelHTML+="        <p>Left panel content goes here</p>";panelHTML+="      </div>";panelHTML+="    </div>";panelHTML+="    \x3c!-- Right panel with cover effect--\x3e";panelHTML+='    <div class="panel panel-right panel-cover">';panelHTML+='      <div class="content-block">';panelHTML+="        <p>Right panel content goes here</p>";panelHTML+="      </div>";
panelHTML+="    </div>";var scriptHTML=document.getElementById("main-body").innerHTML;document.getElementById("main-body").innerHTML=panelHTML+viewHTML+popupHTML+scriptHTML;$$("#new-feed-tab").on("show",function(){mainPostPageTab="new";workingList=newPostList});$$("#hot-feed-tab").on("show",function(){mainPostPageTab="hot";workingList=postList});var ptrContent=$$(".pull-to-refresh-content");ptrContent.on("refresh",function(e){setTimeout(function(){refreshMacro()},200)});
var myApp=new Framework7({onPageBack:function(app){try{document.getElementById("reply-input").blur()}catch(err){}},onPageAfterAnimation:function(app,page){if(page.name=="index"){myApp.destroyPullToRefresh(".pull-to-refresh-content");myApp.initPullToRefresh(".pull-to-refresh-content");if(mainPostPageTab=="hot"){workingList=postList;updateListHTMLFromListData(workingList,"post-list")}else if(mainPostPageTab=="new"){workingList=newPostList;updateListHTMLFromListData(workingList,"new-post-list")}}if(page.name==
"inbox")workingList=notificationList;if(page.name=="user")workingList=userPostList;if(page.name=="post"){$("#reply-input").autoGrow();jQuery("#reply-toolbar").css("height","63px");jQuery("#reply-toolbar").css("padding-bottom","43px");try{Keyboard.hideFormAccessoryBar(true)}catch(err){}$("#reply-input").keydown(function(){if(jQuery("#reply-toolbar").height()!=jQuery(".autogrow-textarea-mirror").height()&&jQuery(".autogrow-textarea-mirror").height()<=70&&jQuery(".autogrow-textarea-mirror").height()>
17){jQuery("#reply-toolbar").css("height",jQuery(".autogrow-textarea-mirror").height()+40);jQuery("#reply-toolbar").css("padding-bottom",jQuery(".autogrow-textarea-mirror").height()+20)}})}},tapHold:true,modalTitle:"\u6ca1\u516d\u513f"});var mainView=myApp.addView(".view-main",{dynamicNavbar:true,domCache:true});
function addNewPost(){var buttons=[{text:"\u53d1\u94fe\u63a5",onClick:function(){addPostPopupOpen()}},{text:"\u53d1\u56fe\u7247",onClick:function(){photoShoot("album")}}];myApp.actions(buttons)}try{if(cordova)loginStatusUpdate()}catch(err){loginStatusUpdate()}var clearCacheSuccess=function(status){myApp.alert("Message: "+status)};var clearCacheError=function(status){myApp.alert("Error: "+status)};
document.addEventListener("deviceready",function(){loginStatusUpdate();udid=device.uuid;try{StatusBar.backgroundColorByHexString("#f7f7f7")}catch(err$0){}document.addEventListener("resume",appReturnedFromBackground,false);function appReturnedFromBackground(){loginStatusUpdate();myApp.destroyPullToRefresh(".pull-to-refresh-content");myApp.initPullToRefresh(".pull-to-refresh-content")}window.addEventListener("statusTap",function(){});var push=PushNotification.init({android:{senderID:"12345679"},ios:{alert:"true",
badge:true,sound:"false",clearBadge:true},windows:{}});push.on("registration",function(data){device_token=data.registrationId});push.on("notification",function(data){if(data.additionalData.type=="1")getUnreadNum();else if(data.additionalData.type=="2");else if(data.additionalData.type=="999")window.cache.clear(clearCacheSuccess,clearCacheError);console.log(data.message);console.log(data.title);console.log(data.count);console.log(data.sound);console.log(data.image);console.log(data.additionalData);
push.finish(function(){console.log("processing of push data is finished")})});push.on("error",function(e){console.log("push error")})},false);
function postPicture(){var options=new FileUploadOptions;options.fileKey="file";options.fileName=fileURL.substr(fileURL.lastIndexOf("/")+1);options.mimeType="image/jpeg";options.chunkedMode=false;var params={};params.token=localStorage.usertoken;params.name=document.getElementById("post-image-title-input").value;params.description="";params.type=2;params.udid=udid;options.params=params;var ft=new FileTransfer;var win=function(r){myApp.hideIndicator();myApp.alert("\u592a6\u4e86\uff01\u53d1\u9001\u6210\u529f");
console.log(r);myApp.closeModal(".popup-post-image")};var fail=function(error){myApp.hideIndicator();myApp.alert("\u7f51\u7edc\u95ee\u9898\uff0c\u8bf7\u91cd\u8bd5\uff01")};myApp.showIndicator();ft.upload(fileURL,encodeURI("http://meiliuer.com/api/createImagePost"),win,fail,options,true)}function refreshMacro(){currentIndex=1;newCurrentIndex=1;updateListDataFromServer();getUnreadNum()}
function photoShoot(option){if(navigator.camera&&option=="album")navigator.camera.getPicture(onSuccess,onFail,{quality:10,destinationType:Camera.DestinationType.FILE_URI,sourceType:Camera.PictureSourceType.SAVEDPHOTOALBUM,correctOrientation:true});else if(navigator.camera)navigator.camera.getPicture(onSuccess,onFail,{quality:10,destinationType:Camera.DestinationType.FILE_URI,correctOrientation:true});else myApp.alert("\u60a8\u7684\u8bbe\u7f6e\u4e0d\u652f\u6301\u7167\u76f8\u673a\uff0c\u8bf7\u5230\u3010\u8bbe\u7f6e\u3011\u4e2d\u6253\u5f00app\u5bf9\u76f8\u673a\u7684\u652f\u6301\uff01")}
function onSuccess(imageData){fileURL=imageData;myApp.popup(".popup-post-image");document.getElementById("post-image-title-input").value="";document.getElementById("post-image-preview").src=fileURL}function onFail(message){}
function forgetPassword(){function validateEmail(email){var re=/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;return re.test(email)}myApp.prompt("\u8bf7\u8f93\u5165\u60a8\u7684\u90ae\u7bb1\uff0c\u6211\u4eec\u5e2e\u4f60\u627e\u56de\u5bc6\u7801",function(value){if(!validateEmail(value)){myApp.alert("\u60a8\u7684\u90ae\u7bb1\u4e0d\u7b26\u5408\u89c4\u8303\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165\uff1a\uff09");return}var ajaxUrl="http://meiliuer.com/api/forgetPassword?email="+
value;$.ajax({url:ajaxUrl,type:"GET",dataType:"jsonp",success:function(results){myApp.alert("\u8bf7\u67e5\u6536\u60a8\u7684\u90ae\u4ef6")}})})}
function postText(){var text=document.getElementById("post-text-input").value;if(localStorage.usertoken==null||localStorage.usertoken=="null"){myApp.alert("\u8bf7\u60a8\u5148\u6ce8\u518c\uff01");return}if(!/\S/.test(text)){myApp.alert("\u6807\u9898\u680f\u4e0d\u80fd\u4e3a\u7a7a");return}var ut=localStorage.usertoken;myApp.showIndicator();var postGetUrl="http://meiliuer.com/api/create?token="+ut+"&"+"name="+encodeURIComponent(text)+"&type=2&description=&callback=1&encoded=1";$.ajax({url:postGetUrl,
type:"POST",dataType:"jsonp",success:function(json){myApp.hideIndicator();console.log(json);myApp.alert("\u53d1\u9001\u6210\u529f",function(){myApp.closeModal(".popup-post-text");updateListDataFromServer()})},timeout:3E4,error:function(json){myApp.hideIndicator();myApp.alert("\u53d1\u9001\u5931\u8d25")}})}
function replyToComment(commentId,postId,userId,userName,content){console.log(postId);var userQuery="";var userPrefix="";console.log(userId);if(userId!="")userQuery="&receiver="+userId;var urlPost="http://meiliuer.com/api/createReply?token="+localStorage.usertoken+"&comment_id="+commentId+"&description="+encodeURIComponent(content)+userQuery;$.ajax({url:urlPost,type:"GET",dataType:"jsonp",success:function(json){postPage(postId);$("#reply-input").height(17);jQuery("#reply-toolbar").css("height","63px");
jQuery("#reply-toolbar").css("padding-bottom","43px")}});for(var i=0;i<commentList.length;i++)if(commentList[i].comment_id==commentId){var elem={avatar:"",create_time:0,description:content,reply_id:0,user_id:0,username:localStorage.usernickname};commentList[i].replies.push(elem);postPageUI(commentList,postId)}function replyCallback(){postPage(postId)}}
function commentToPost(postId,content){var urlPost="http://meiliuer.com/api/createComment?token="+localStorage.usertoken+"&post_id="+postId+"&description="+content+"&callback=1";$.ajax({url:urlPost,dataType:"jsonp",type:"GET",success:function(json){postPage(postId);$("#reply-input").height(17);jQuery("#reply-toolbar").css("height","63px");jQuery("#reply-toolbar").css("padding-bottom","43px")}});var elem={avatar:"",comment_id:0,create_time:0,description:content,down:0,replies:[],up:0,user_id:0,username:localStorage.usernickname};
commentList.push(elem);postPageUI(commentList,postId)}
function getReplyInputBoxHTML(){return""+'              <div class="list-block media-list" id="comment-list"> '+"                <ul> "+"                </ul> "+"              </div> "+"            </div>  "+'        <div class="toolbar" id="reply-toolbar" > '+'          <div class="toolbar-inner bg-gray" data-page="post"> '+'            <div class="list-block" style="background:transparent;width:100%; "  > '+'              <ul style="background:transparent;"> '+"                <li> "+'                 <div class="item-content" style="padding-left: 0px"> '+
'                   <div class="item-inner" style="padding-right: 0px"> '+'                     <div class="item-media"><i class="fa fa-commenting-o comment-icon"></i></div> '+'                     <div class="item-input"> '+'                         <textarea type="text" id="reply-input"  name="reply" placeholder="\u8bf4\u70b9\u5565\u3002\u3002\u3002"></textarea> '+"                     </div> "+"                   </div> "+"                 </div> "+"                </li> "+"              </ul> "+
"            </div> "+"          </div> ";"        </div> "}function adjustPictureWidthAndHeight(){$(".pic-post-unit").css("width",picProportion*100+"%");$(".pic-post-unit").css("height",$(".big-post-image").width());$(".pic-post-unit .post-author-image").css("left",12);$$(".index-image-preview").on("taphold",function(e){console.log(this.src);var myPhotoBrowserPopupDark=myApp.photoBrowser({photos:[this.src],theme:"dark",navbar:false,toolbar:false});myPhotoBrowserPopupDark.open()})}
function openPostPageByElem(elem,index,listName){if(localStorage.usertoken==null||localStorage.usertoken=="null"){myApp.alert("\u8bf7\u5148\u767b\u5f55\u540e\u518d\u8bc4\u8bba~");return}mainView.router.loadPage({"pageName":"post"});postPage(elem.post_id);targetPostId=elem.post_id;var voteUpCSS="";var voteDownCSS="";if(elem.self_vote==1)voteUpCSS=" voted-block ";else if(elem.self_vote==2)voteDownCSS=" voted-block ";var outPutHTML="<div class='page-content'><div id='post-page-title-cell' class='list-block'><ul>";
outPutHTML+=getListHTMLFromElem(elem,index,listName);outPutHTML+="</ul></div> ";outPutHTML+=getReplyInputBoxHTML();document.getElementById("post-page").innerHTML=outPutHTML;document.getElementById("comment-list").innerHTML="<div class='post-page-no-comment-placeholder'>\u6b63\u5728\u52a0\u8f7d...</div>";adjustPictureWidthAndHeight();setTimeout(function(){setIsCommentToPostToTrue();document.getElementById("reply-input").onkeypress=function(e){if(e.keyCode==13&&document.getElementById("reply-input").value!=
"")sendMacro(targetPostId,targetCommentId)}},400)}function openPostPageByIndex(index){stopBubbling(this.event);if(localStorage.usertoken==null||localStorage.usertoken=="null"){myApp.alert("\u8bf7\u5148\u767b\u5f55\u540e\u518d\u8bc4\u8bba~");return}var listName="post-page";mainView.router.loadPage({"pageName":"post"});postPage(workingList[index].post_id);targetPostId=workingList[index].post_id;openPostPageByElem(workingList[index],index,listName)}
function setIsCommentToPostToTrue(){document.getElementById("reply-input").placeholder="\u56de\u590d\uff1a";isCommentToPost=true}
function setCommentToPostState(){stopBubbling(this.event);setIsCommentToPostToTrue();document.getElementById("reply-toolbar").style.display="block";document.getElementById("reply-input").placeholder="\u56de\u590d\uff1a";try{Keyboard.hideFormAccessoryBar(true);Keyboard.disableScrollingInShrinkView(true)}catch(error){}setTimeout(function(){document.getElementById("reply-input").focus()},100)}
function sendMacro(postId,commentId){var repliedContent=document.getElementById("reply-input").value;document.getElementById("reply-input").value="";if(isCommentToPost)commentToPost(postId,repliedContent);else replyToComment(targetCommentId,targetPostId,targetUserId,targetUsername,repliedContent);document.getElementById("reply-input").blur()}
function setReplyToCommentState(commentId,postId,index,userId,userName){setTimeout(function(){if(hasClickedGetUserPost){hasClickedGetUserPost=false;return}if(userId!=null)document.getElementById("reply-input").placeholder="@"+userName;else document.getElementById("reply-input").placeholder="@"+commentList[index].username;try{Keyboard.hideFormAccessoryBar(true);Keyboard.disableScrollingInShrinkView(true)}catch(err$0){}setTimeout(function(){document.getElementById("reply-input").focus()},200);isCommentToPost=
false;targetPostId=postId;targetCommentId=commentId;targetUserId=userId||"";targetUsername=userName||""},10)}
function voteComment(index,type){if(localStorage.usertoken==null||localStorage.usertoken=="null"){myApp.alert("\u8bf7\u5148\u767b\u5f55\u540e\u518d\u6295\u7968~");return}var postUrl="";if(commentList[index].self_vote==1&&type==1){$("#comment-voting-down-arrow-"+index).removeClass("voted-block");$("#comment-voting-up-arrow-"+index).removeClass("voted-block");commentList[index].up--;commentList[index].self_vote=0;postUrl="http://meiliuer.com/api/VoteCommentCancel?token="+localStorage.usertoken+"&type="+
type+"&comment_id="+commentList[index].comment_id}else if(commentList[index].self_vote==2&&type==2){commentList[index].down--;$("#comment-voting-down-arrow-"+index).removeClass("voted-block");$("#comment-voting-up-arrow-"+index).removeClass("voted-block");commentList[index].self_vote=0;postUrl="http://meiliuer.com/api/VoteCommentCancel?token="+localStorage.usertoken+"&type="+type+"&comment_id="+commentList[index].comment_id}else if(commentList[index].self_vote==0){if(type==1){$("#comment-voting-down-arrow-"+
index).removeClass("voted-block");$("#comment-voting-up-arrow-"+index).addClass("voted-block");commentList[index].up++}else{$("#comment-voting-down-arrow-"+index).addClass("voted-block");$("#comment-voting-up-arrow-"+index).removeClass("voted-block");commentList[index].down++}postUrl="http://meiliuer.com/api/voteComment?token="+localStorage.usertoken+"&type="+type+"&comment_id="+commentList[index].comment_id}else if(commentList[index].self_vote==2&&type==1){commentList[index].up++;commentList[index].down--;
$("#comment-voting-down-arrow-"+index).removeClass("voted-block");$("#comment-voting-up-arrow-"+index).addClass("voted-block");postUrl="http://meiliuer.com/api/voteComment?token="+localStorage.usertoken+"&type="+type+"&comment_id="+commentList[index].comment_id}else if(commentList[index].self_vote==1&&type==2){commentList[index].up--;commentList[index].down++;$("#comment-voting-down-arrow-"+index).addClass("voted-block");$("#comment-voting-up-arrow-"+index).removeClass("voted-block");postUrl="http://meiliuer.com/api/voteComment?token="+
localStorage.usertoken+"&type="+type+"&comment_id="+commentList[index].comment_id}document.getElementById("comment-voting-number-"+index).innerHTML=commentList[index].up-commentList[index].down;$.ajax({url:postUrl,dataType:"jsonp",jsonpCallback:"haha",success:function(results){if(type==1)console.log("voted up");else console.log("voted down")}})}
function postPageUI(results,postId){var listName="comment-";if(results.length==0)document.getElementById("comment-list").innerHTML="<div class='post-page-no-comment-placeholder'>\u6682\u65f6\u6ca1\u6709\u8bc4\u8bba</div>";else{var liHTML="<ul>";for(var i=0;i<results.length;i++){var voteUpCSS="";var voteDownCSS="";if(results[i].self_vote==1)voteUpCSS=" voted-block ";else if(results[i].self_vote==2)voteDownCSS=" color-meiliuer-yellow ";liHTML+="<li> "+'  <div href="#" class="post-comment item-content"  > '+
'    <div class="item-media"><img src="http://meiliuer.com'+results[i].avatar+'" width="44" style="border-radius:44px;"></div> '+'    <div class="item-inner" onclick = "setReplyToCommentState('+results[i].comment_id+", "+postId+", "+i+')" > '+'      <div class="item-title-row"> '+'        <div class="item-title name-link" onclick="getUserPost('+results[i].user_id+')">'+results[i].username+"</div> "+"      </div> "+'      <div class="item-subtitle" data-user-id="'+results[i].user_id+'" data-post-id="'+
postId+'"  data-comment-id="'+results[i].comment_id+'" >'+results[i].description+"</div> "+"    </div> "+"  </div> "+'     <div class = "'+listName+'post-voting-area"> '+'       <div onclick="voteComment('+i+',1)" id="'+listName+"voting-up-arrow-"+i+'" class="vote-up-block '+voteUpCSS+' ">'+'        <i class="fa fa-caret-up fa-2x "  ></i> '+'        <div class="post-voting-text" id="'+listName+"voting-number-"+i+'">'+(results[i].up-results[i].down)+"</div> "+"       </div>"+"     </div>";"</li> ";
for(var j=0;j<results[i].replies.length;j++)liHTML+=""+"<li> "+'  <div href="#" class=" item-content post-reply"  > '+'    <div class="item-inner" onclick="setReplyToCommentState('+results[i].comment_id+", "+postId+", "+i+", "+results[i].replies[j].user_id+", '"+results[i].replies[j].username+"')\" > "+'      <div class="item-title-row"> '+'        <div class="item-title " ><span class="name-link" onclick="getUserPost('+results[i].replies[j].user_id+')">'+results[i].replies[j].username+"</span>"+
(results[i].replies[j].receiver_username?" @ "+'<span class="name-link" onclick="getUserPost('+results[i].replies[j].receiver_id+')">'+results[i].replies[j].receiver_username+"</span>":"")+": </div> "+"      </div> "+'      <div class="item-subtitle" data-user-id="'+results[i].replies[j].user_id+'"  data-post-id="'+postId+'" data-comment-id="'+results[i].comment_id+'" data-reply-id="'+results[i].replies[j].reply_id+'">'+results[i].replies[j].description+'</div><div class="reply-placeholder"></div> '+
"    </div> "+"  </div> "+"</li> "}document.getElementById("comment-list").innerHTML=liHTML+"</ul>"}$$(".post-comment .item-subtitle").on("taphold",function(e){haha=this;var userId=$(haha).data().userId;if(userId==localStorage.userId){var buttons=[{text:"Delete",color:"red",onClick:function(){var postId=$(haha).data().postId;var commentId=$(haha).data().commentId;deleteComment(postId,commentId)}}];myApp.actions(buttons)}});$$(".post-reply .item-subtitle").on("taphold",function(e){haha=this;var userId=
$(haha).data().userId;if(userId==localStorage.userId){var buttons=[{text:"Delete",color:"red",onClick:function(){var postId=$(haha).data().postId;var commentId=$(haha).data().commentId;var replyId=$(haha).data().replyId;deleteReply(postId,replyId)}}];myApp.actions(buttons)}})}
function deletePost(postId){console.log(postId);myApp.confirm("\u4f60\u786e\u5b9a\u8981\u5220\u9664\u5417\uff1f\u8fd9\u6761\u770b\u7740\u4e0d\u9519\u54e6~",function(){$.ajax({url:"http://meiliuer.com/api/delete?post_id="+postId+"&token="+localStorage.usertoken,dataType:"jsonp",type:"GET",success:function(results){mainView.router.back();updateListDataFromServer()}})})}
function deleteReply(postId,replyId){console.log(replyId);myApp.confirm("\u4f60\u786e\u5b9a\u8981\u5220\u9664\u5417\uff1f\u8fd9\u6761\u770b\u7740\u4e0d\u9519\u54e6~",function(){for(var i in commentList)for(var j in commentList[i].replies)if(commentList[i].replies[j].reply_id==replyId){console.log(replyId);commentList[i].replies.splice(j,1);setTimeout(function(){postPageUI(commentList,postId)},200);break}$.ajax({url:"http://meiliuer.com/api/deleteReply?reply_id="+replyId+"&token="+localStorage.usertoken,
dataType:"jsonp",type:"GET",success:function(results){}})})}
function deleteComment(postId,commentId){console.log(commentId);myApp.confirm("\u4f60\u786e\u5b9a\u8981\u5220\u9664\u5417\uff1f\u8fd9\u6761\u770b\u7740\u4e0d\u9519\u54e6~",function(){for(var i in commentList)if(commentList[i].comment_id==commentId){console.log(commentList[i]);commentList.splice(i,1);setTimeout(function(){postPageUI(commentList,postId)},200);break}$.ajax({url:"http://meiliuer.com/api/deleteComment?comment_id="+commentId+"&token="+localStorage.usertoken,dataType:"jsonp",type:"GET",
success:function(results){console.log("good")}})})}function stopBubbling(evt){evt.stopPropagation();evt.cancelBubble=true}function postPage(postId){$.ajax({url:"http://meiliuer.com/api/getallcomments?post_id="+postId+"&token="+localStorage.usertoken,dataType:"jsonp",type:"GET",success:function(results){commentList=results;postPageUI(commentList,postId)}})}
function getListHTMLFromElem(elem,index,listName){var index=index||0;var listName=listName?listName+"-":"";var voteUpCSS="";var voteDownCSS="";if(elem.self_vote==1)voteUpCSS=" voted-block ";else if(elem.self_vote==2)voteDownCSS=" voted-block ";var replyHTML="";var shareDeleteHTML="";var descriptionHTML="";descriptionHTML="<div onclick = 'openElem("+index+")' class='post-description-text'>"+elem.description+"</div>";if(mainView.url=="#post"){replyHTML='<div class="col-33 " style = "text-align:center;" onclick = "setCommentToPostState ()">\u56de\u590d</div>';
console.log(elem.description)}else replyHTML='<div class="col-33 " style = "text-align:center;" onclick = "openPostPageByIndex('+index+')">\u8bc4\u8bba('+elem.comments+")</div>";if(elem.user_id==localStorage.user_id&&mainView.url=="#post")shareDeleteHTML='         <div class="col-33 " style = "text-align:center;" onclick="deletePost('+elem.post_id+')">\u5220\u9664</div>';else shareDeleteHTML='         <div class="col-33 " style = "text-align:center;" onclick="shareByCopying('+index+",'"+listName+
"')\">\u5206\u4eab</div>";if(elem.type==1)return'   <li class="post-unit item-link" id="'+listName+"post-unit-id-"+index+'" onclick="openPostPageByIndex('+index+')" > '+'    <img onclick = "openElem('+index+')"  class =  "post-image" onerror="this.onerror = null; this.src= \'img/half_trans_solid.png\' " src="http://meiliuer.com'+elem.thumb_pic+'">'+'     <div class="post-unit-textblock" > '+'       <a class = "post-title " onclick = "openElem('+index+')">'+'<i style="color:#AAA; " class="fa fa-link"></i> '+
elem.title+"</a> "+"     </div> "+'       <img class = "post-author-image"  src="http://meiliuer.com'+elem.avatar+'">'+'       <div class = "row comment-share-bar">'+'         <div class="col-33 " onclick="getUserPost('+elem.user_id+')" >'+"           <span>"+elem.username+"           </span>"+"         </div>"+replyHTML+shareDeleteHTML+"       </div> "+'       <div class = "post-voting-area"> '+'         <div onclick="voteUp('+index+')" id="'+listName+"voting-up-arrow-"+index+'" class="vote-up-block '+
voteUpCSS+' ">'+'          <i class="fa fa-caret-up fa-2x "  ></i> '+'          <div class="post-voting-text" id="'+listName+"voting-number-"+index+'">'+(elem.up-elem.down)+"\t\t</div> "+"         </div>"+'         <div onclick="voteDown('+index+')" class="vote-down-block '+voteDownCSS+' " id="'+listName+"voting-down-arrow-"+index+'">'+'           <i class="fa fa-caret-down fa-2x  "  ></i> '+"         </div> "+"       </div>"+"   </li> ";else if(elem.type==2){console.log("type 2");var className="";
return'   <li class="pic-post-unit item-link" id="'+listName+"post-unit-id-"+index+'"  > '+'     <div class="pic-post-unit-textblock" > '+'       <a class = "post-title item-link" onclick = "openElem('+index+')">'+elem.title+"</a> "+"     </div> "+'       <img class = "post-author-image"  src="http://meiliuer.com'+elem.avatar+'">'+'       <div class = "row comment-share-bar content-share-bar">'+'         <div class="col-33 " onclick="getUserPost('+elem.user_id+')" >'+"           <span>"+elem.username+
"           </span>"+"         </div>"+replyHTML+shareDeleteHTML+"       </div> "+'       <div class = "post-voting-area post-page-voting-area"> '+'         <div onclick="voteUp('+index+')" id="'+listName+"voting-up-arrow-"+index+'" class="vote-up-block '+voteUpCSS+' ">'+'          <i class="fa fa-caret-up fa-2x "  ></i> '+'          <div class="post-voting-text" id="'+listName+"voting-number-"+index+'">'+(elem.up-elem.down)+"\t\t\t</div> "+"         </div>"+'         <div onclick="voteDown('+index+
')" class="vote-down-block '+voteDownCSS+' " id="'+listName+"voting-down-arrow-"+index+'">'+'           <i class="fa fa-caret-down fa-2x  "  ></i> '+"         </div> "+"       </div>"+descriptionHTML+"   </li> "}else if(elem.type==2&&mainView.url=="#index"){var className="index-image-preview";return'   <li class="post-unit item-link" id="'+listName+"post-unit-id-"+index+'" onclick="openPostPageByIndex('+index+')" > '+'    <img onclick = "openElem('+index+')"  class =  " index-image-preview post-image" onerror="this.onerror = null; this.src= \'img/half_trans_solid.png\' " src="http://meiliuer.com'+
elem.thumb_pic+'">'+'     <div class="post-unit-textblock" > '+'       <a class = "post-title " onclick = "openPostPageByIndex('+index+')">'+elem.title+"</a> "+"     </div> "+'       <img class = "post-author-image"  src="http://meiliuer.com'+elem.avatar+'">'+'       <div class = "row comment-share-bar">'+'         <div class="col-33 " onclick="getUserPost('+elem.user_id+')" >'+"           <span>"+elem.username+"           </span>"+"         </div>"+replyHTML+shareDeleteHTML+"       </div> "+'       <div class = "post-voting-area"> '+
'         <div onclick="voteUp('+index+')" id="'+listName+"voting-up-arrow-"+index+'" class="vote-up-block '+voteUpCSS+' ">'+'          <i class="fa fa-caret-up fa-2x "  ></i> '+'          <div class="post-voting-text" id="'+listName+"voting-number-"+index+'">'+(elem.up-elem.down)+"</div> "+"         </div>"+'         <div onclick="voteDown('+index+')" class="vote-down-block '+voteDownCSS+' " id="'+listName+"voting-down-arrow-"+index+'">'+'           <i class="fa fa-caret-down fa-2x  "  ></i> '+"         </div> "+
"       </div>"+descriptionHTML+"   </li> "}else return'   <li class="post-unit item-link" id="'+listName+"post-unit-id-"+index+'"  > '+'    <img onclick = "openElem('+index+')"  class =  "post-image" onerror="this.onerror = null; this.src= \'img/half_trans_solid.png\' " src="http://meiliuer.com'+elem.thumb_pic+'">'+'     <div class="post-unit-textblock" > '+'       <a class = "post-title " onclick = "openPostPageByIndex('+index+')">'+elem.title+"</a> "+"     </div> "+'       <img class = "post-author-image"  src="http://meiliuer.com'+
elem.avatar+'">'+'       <div class = "row comment-share-bar">'+'         <div class="col-33 " onclick="getUserPost('+elem.user_id+')" >'+"           <span>"+elem.username+"           </span>"+"         </div>"+replyHTML+shareDeleteHTML+"       </div> "+'       <div class = "post-voting-area"> '+'         <div onclick="voteUp('+index+')" id="'+listName+"voting-up-arrow-"+index+'" class="vote-up-block '+voteUpCSS+' ">'+'          <i class="fa fa-caret-up fa-2x "  ></i> '+'          <div class="post-voting-text" id="'+
listName+"voting-number-"+index+'">'+(elem.up-elem.down)+"</div> "+"         </div>"+'         <div onclick="voteDown('+index+')" class="vote-down-block '+voteDownCSS+' " id="'+listName+"voting-down-arrow-"+index+'">'+'           <i class="fa fa-caret-down fa-2x  "  ></i> '+"         </div> "+"       </div>"+descriptionHTML+"   </li> "}
function shareByCopying(index,list){stopBubbling(this.event);try{var shareURL="http://meiliuer.com/posts/"+workingList[index].post_id;window.plugins.socialsharing.share(null,workingList[index].title+" - \u6ca1\u516d\u513f",null,shareURL)}catch(err$2){var buttons=[{text:"\u590d\u5236\u5230\u526a\u8d34\u677f",onClick:function(){try{var text=workingList[index].title+" - \u6ca1\u516d\u513f: "+shareURL;cordova.plugins.clipboard.copy(text);var appToast=new Framework7;var toast=appToast.toast("\u5df2\u590d\u5236",
'<i class="fa fa-check"></i>',{});toast.show()}catch(err$1){}}}];myApp.actions(buttons)}}function animateEffect(selector,effect){$(selector).addClass("animated "+effect);setTimeout(function(){$(selector).removeClass("animated "+effect)},1E3)}
function voteUp(index){stopBubbling(this.event);if(localStorage.usertoken==null||localStorage.usertoken=="null"){myApp.alert("\u8bf7\u5148\u767b\u5f55\u540e\u518d\u6295\u7968~");return}var postGetUrl="";var ut=localStorage.usertoken;var postId=workingList[index].post_id;if(workingList[index].self_vote==1){workingList[index].up--;var number=workingList[index].up-workingList[index].down;votingCSS(index,number,0);workingList[index].self_vote=0;postGetUrl="http://meiliuer.com/api/VoteCancel?token="+ut+
"&post_id="+postId+"&type=1"}else if(workingList[index].self_vote==2){workingList[index].up++;workingList[index].down--;var number=workingList[index].up-workingList[index].down;votingCSS(index,number,1);workingList[index].self_vote=1;postGetUrl="http://meiliuer.com/api/vote?token="+ut+"&post_id="+postId+"&type=1"}else{workingList[index].up++;var number=workingList[index].up-workingList[index].down;votingCSS(index,number,1);workingList[index].self_vote=1;postGetUrl="http://meiliuer.com/api/vote?token="+
ut+"&post_id="+postId+"&type=1"}responseObject=$.ajax({url:postGetUrl,type:"GET",dataType:"jsonp",success:function(results){console.log(results)}})}
function votingCSS(index,newVote,newState){if(newState==0){$("#user-post-list-voting-up-arrow-"+index).removeClass("voted-block");$("#user-post-list-voting-down-arrow-"+index).removeClass("voted-block");$("#post-page-voting-up-arrow-"+index).removeClass("voted-block");$("#post-page-voting-down-arrow-"+index).removeClass("voted-block");$("#post-list-voting-up-arrow-"+index).removeClass("voted-block");$("#post-list-voting-down-arrow-"+index).removeClass("voted-block");$("#new-post-list-voting-up-arrow-"+
index).removeClass("voted-block");$("#new-post-list-voting-down-arrow-"+index).removeClass("voted-block");$("#new-post-list-voting-number-"+index).html(newVote);$("#post-list-voting-number-"+index).html(newVote);$("#user-post-list-voting-number-"+index).html(newVote);$("#post-page-voting-number-"+index).html(newVote)}else if(newState==1){$("#user-post-list-voting-up-arrow-"+index).addClass("voted-block");$("#user-post-list-voting-down-arrow-"+index).removeClass("voted-block");$("#post-page-voting-up-arrow-"+
index).addClass("voted-block");$("#post-page-voting-down-arrow-"+index).removeClass("voted-block");$("#post-list-voting-up-arrow-"+index).addClass("voted-block");$("#post-list-voting-down-arrow-"+index).removeClass("voted-block");$("#new-post-list-voting-up-arrow-"+index).addClass("voted-block");$("#new-post-list-voting-down-arrow-"+index).removeClass("voted-block");$("#new-post-list-voting-number-"+index).html(newVote);$("#post-list-voting-number-"+index).html(newVote);$("#user-post-list-voting-number-"+
index).html(newVote);$("#post-page-voting-number-"+index).html(newVote)}else{$("#user-post-list-voting-up-arrow-"+index).removeClass("voted-block");$("#user-post-list-voting-down-arrow-"+index).addClass("voted-block");$("#post-page-voting-up-arrow-"+index).removeClass("voted-block");$("#post-page-voting-down-arrow-"+index).addClass("voted-block");$("#post-list-voting-up-arrow-"+index).removeClass("voted-block");$("#post-list-voting-down-arrow-"+index).addClass("voted-block");$("#new-post-list-voting-up-arrow-"+
index).removeClass("voted-block");$("#new-post-list-voting-down-arrow-"+index).addClass("voted-block");$("#new-post-list-voting-number-"+index).html(newVote);$("#post-list-voting-number-"+index).html(newVote);$("#user-post-list-voting-number-"+index).html(newVote);$("#post-page-voting-number-"+index).html(newVote)}}
function voteDown(index){stopBubbling(this.event);if(localStorage.usertoken==null||localStorage.usertoken=="null"){myApp.alert("\u8bf7\u5148\u767b\u5f55\u540e\u518d\u6295\u7968~");return}var postGetUrl="";var postId=workingList[index].post_id;var ut=localStorage.usertoken;if(workingList[index].self_vote==2){workingList[index].down--;var number=workingList[index].up-workingList[index].down;votingCSS(index,number,0);workingList[index].self_vote=0;postGetUrl="http://meiliuer.com/api/VoteCancel?token="+
ut+"&post_id="+postId+"&type=2"}else if(workingList[index].self_vote==1){workingList[index].up--;workingList[index].down++;var number=workingList[index].up-workingList[index].down;votingCSS(index,number,2);workingList[index].self_vote=2;postGetUrl="http://meiliuer.com/api/vote?token="+ut+"&post_id="+postId+"&type=2"}else{workingList[index].down++;var number=workingList[index].up-workingList[index].down;votingCSS(index,number,2);workingList[index].self_vote=2;postGetUrl="http://meiliuer.com/api/vote?token="+
ut+"&post_id="+postId+"&type=2"}responseObject=$.ajax({url:postGetUrl,type:"GET",dataType:"jsonp",success:function(results){console.log(results)}})}
function updateListHTMLFromListData(results,listName,placeholder){if(!placeholder)placeholder="";if(results.length>0){var postListHTML="<ul>";for(var i in results){var elem=results[i];postListHTML+=getListHTMLFromElem(elem,i,listName)}document.getElementById(listName).innerHTML=postListHTML+"</ul>"}else document.getElementById(listName).innerHTML="<div style='margin: 20px 0px;text-align: center;color:#aaaaaa '>"+placeholder+"</div>";adjustPictureWidthAndHeight()}
function updateListDataFromServer(){loadCarmaNumber();var postGetUrl="http://meiliuer.com/api/weeklyindex?udid="+udid+"&page="+newCurrentIndex+"&token="+localStorage.usertoken+"&device_token="+device_token+"device_type=iOS";responseObject=$.ajax({url:postGetUrl,type:"GET",dataType:"jsonp",success:function(json){postList=json;if(mainPostPageTab=="hot"){workingList=postList;updateListHTMLFromListData(workingList,"post-list")}else if(mainPostPageTab=="new"){workingList=newPostList;updateListHTMLFromListData(workingList,
"new-post-list")}updateListHTMLFromListData(json,"post-list");myApp.pullToRefreshDone()},error:function(err){myApp.pullToRefreshDone()}});var newPostGetURL="http://meiliuer.com/api/index?udid="+udid+"&page="+currentIndex+"&token="+localStorage.usertoken+"&device_token="+device_token+"device_type=iOS";responseObject=$.ajax({url:newPostGetURL,type:"GET",dataType:"jsonp",success:function(json){newPostList=json;if(mainPostPageTab=="hot"){workingList=postList;updateListHTMLFromListData(workingList,"post-list")}else if(mainPostPageTab==
"new"){workingList=newPostList;updateListHTMLFromListData(workingList,"new-post-list")}updateListHTMLFromListData(json,"new-post-list");myApp.pullToRefreshDone()},error:function(err){myApp.pullToRefreshDone()}})}
function openElem(index){stopBubbling(this.event);$(".post-unit").css("border-left","none");$("#post-list-post-unit-id-"+index).css("border-left","5px solid #fde125");if(workingList[index].type==1)openUrl(workingList[index].url,true);else if(workingList[index].type==2){console.log(workingList[index].description);var imageURL=workingList[index].description.match(/src=(.+?[\.jpg|\.gif|\.png]")/)[1].replace(/"/g,"");console.log(imageURL);console.log("http://meiliuer.com/"+workingList[index].thumb_pic);
var myPhotoBrowserPopupDark=myApp.photoBrowser({photos:[imageURL],zoom:false,theme:"dark",swipeToClose:false,navbar:false,toolbar:false,onTap:function(swiper,event){myPhotoBrowserPopupDark.close()}});myPhotoBrowserPopupDark.open()}else openPostPageByIndex(index)}
function carmaPopover(){console.log("ASdf");var carma=document.getElementById("carma-number").innerHTML;var percentage=Math.max(5,Math.min(100,Math.round(Math.pow(carma,.2)*19)));var popoverHTML='<div class="popover" style="width:80%">'+'<div class="popover-inner">'+'<div class="content-block">'+'<div style="text-align:center;color:#222;font-size:18px;">\u60a8\u7684\u6ca1\u516d\u513f\u79ef\u5206\u662f<span style="color:#B22;">'+carma+"</span></div>"+'<div style="text-align:center;color:#222;font-size:18px;"> \u51fb\u8d25\u4e86\u5168\u56fd<span style="color:#B22;">'+
percentage+"%</span>\u7684\u7f51\u53cb</div>"+'<div style="padding-top:10px;">\u5237\u5206\u5c0f\u8d34\u58eb\uff1a\u53d1\u5e03\u66f4\u591a\u7684\u4e1c\u897f\uff0c\u9001\u51fa\u66f4\u591a\u5408\u7406\u7684\u8d5e\u540c\uff0c\u6536\u5230\u66f4\u591a\u8d5e\u540c\uff0c\u90fd\u4f1a\u8ba9\u60a8\u7684\u79ef\u5206\u8fdb\u6b65\uff01</div>'+"</div>"+"</div>"+"</div>";myApp.popover(popoverHTML,"#carma-number")}
function openUrl(url,readerMode){try{if(AppVersion.version<="1.1")SafariViewController.isAvailable(function(available){if(available)SafariViewController.show({"url":url,"enterReaderModeIfAvailable":readerMode},function(msg){console.log("OK: "+msg)},function(msg){});else var ref=window.open(url,"_blank","location=yes")});else cordova.ThemeableBrowser.open(url,"_blank",{statusbar:{color:"#f7f7f7ff"},toolbar:{height:44,color:"#f7f7f7ff"},title:{color:"#222222ff",showPageTitle:true},closeButton:{wwwImage:"img/oie_m88mDKVqOq7V.png",
wwwImageDensity:3,align:"left",event:"closePressed"},backButtonCanClose:true}).addEventListener("backPressed",function(e){}).addEventListener("helloPressed",function(e){}).addEventListener("sharePressed",function(e){}).addEventListener(cordova.ThemeableBrowser.EVT_ERR,function(e){}).addEventListener(cordova.ThemeableBrowser.EVT_WRN,function(e){})}catch(err$4){try{SafariViewController.isAvailable(function(available){if(available)SafariViewController.show({"url":url,"enterReaderModeIfAvailable":readerMode},
function(msg){console.log("OK: "+msg)},function(msg){});else var ref=window.open(url,"_blank","location=yes")})}catch(err$3){window.open(url,"_blank","location=yes")}}}function configPageOpen(){myApp.popup(".popup-config");if(localStorage.usertoken!="null")document.getElementById("setting-nickname-input").value=localStorage.usernickname;else document.getElementById("setting-nickname-input").value=""}function selfPage(){getUserPost(localStorage.userId,1)}
function configPopupClose(){myApp.closeModal(".popup-config")}var unreadNumber=0;function getUnreadNum(){var ajaxUrl="http://meiliuer.com/api/UnreadNotifications?token="+localStorage.usertoken;console.log(ajaxUrl);$.ajax({url:ajaxUrl,dataType:"jsonp",type:"GET",success:function(json){console.log(json);updateUnreadBadge(json.unread)}})}
function updateUnreadBadge(unreadNumber){if(unreadNumber!=0||unreadNumber!="0"){document.getElementById("unread-badge").style.display="inline-block";document.getElementById("unread-badge").innerHTML=unreadNumber}else document.getElementById("unread-badge").style.display="none"}function inboxPopupOpen(){updateUnreadBadge(0);mainView.router.loadPage({pageName:"inbox",animatePages:false});getNotificationList()}function inboxPopupClose(){mainView.router.back()}
function getSinglePage(postId){updateNotificationListUI();var ajaxUrl="http://meiliuer.com/api/view?post_id="+postId;$.ajax({url:ajaxUrl,type:"GET",dataType:"jsonp",success:function(singlePageJson){console.log(singlePageJson);openPostPageByElem(singlePageJson,0,"post-page")}})}
function notificationListCellUI(elem,index){var typeId=elem.type_id;var isRead=elem.read;var unreadStyleSheet="";var prompt="";if(isRead==0)unreadStyleSheet=" style='background-color: #eee;' ";if(typeId==2)prompt=" \u8bc4\u8bba\u4e86\u4f60\u7684\u5185\u5bb9\uff1a";else if(typeId==3)prompt=" \u56de\u590d\u4e86\u4f60\u7684\u8bc4\u8bba\uff1a";return"   <li> "+'     <a href="#" class=" item-content" '+unreadStyleSheet+" > "+'       <div class="item-media" onclick="getUserPost('+elem.noti_user_id+')" ><img src="http://meiliuer.com'+
elem.noti_avatar+'" width="44" style="border-radius:44px;"></div> '+'       <div class="item-inner"> '+'         <div class="item-title-row"> '+'           <div class="item-title" ><span onclick="getUserPost('+elem.noti_user_id+')" class="name-link">'+elem.noti_username+"</span> "+prompt+"</div> "+"         </div> "+'         <div class="item-text" onclick="openPostPageByIndex ('+index+')">'+elem.post_name+"</div> "+"       </div> "+"     </a> "+"   </li> "}
function updateNotificationListUI(){if(notificationList.length>0){var notificationHTML="<ul>";for(var i=0;i<notificationList.length;i++)notificationHTML+=notificationListCellUI(notificationList[i],i);notificationHTML+="</ul>";document.getElementById("notification-list").innerHTML=notificationHTML}else document.getElementById("notification-list").innerHTML="<div class='post-page-no-comment-placeholder'>\u5f53\u524d\u6ca1\u6709\u63d0\u793a:)</div>"}
function markAllAsRead(){var ajaxUrl="http://meiliuer.com/api/ReadNotifications?token="+localStorage.usertoken;$.ajax({url:ajaxUrl,dataType:"jsonp",type:"GET",success:function(json){console.log(json)}})}
function getNotificationList(){document.getElementById("notification-list").innerHTML="<div class='post-page-no-comment-placeholder'>\u6b63\u5728\u52a0\u8f7d...</div>";var ut=localStorage.usertoken;var postGetUrl="http://meiliuer.com/api/notifications?token="+ut+"&page=1";console.log(postGetUrl);$.ajax({url:postGetUrl,type:"GET",dataType:"jsonp",success:function(json){console.log(json);notificationList=json;workingList=notificationList;updateNotificationListUI();markAllAsRead()}})}
function getThumbPic(postId){$.ajax({url:"http://meiliuer.com/api/SaveTitle?token="+localStorage.usertoken+"&id="+postId,dataType:"jsonp",type:"GET",succcess:function(json){console.log(json)},error:function(error){}})}
function getUrlTitle(){if(!validateUrl(document.getElementById("post-address-input").value)){myApp.alert("\u8bf7\u8f93\u5165\u4e00\u4e2a\u6709\u6548\u7684\u5730\u5740");return}myApp.showPreloader("\u6b63\u5728\u8bfb\u53d6\u6807\u9898");var url=document.getElementById("post-address-input").value;var responseObject=$.ajax({url:"http://meiliuer.com/api/GetTitle?token="+localStorage.usertoken+"&url="+encodeURIComponent(url),dataType:"jsonp",type:"GET",succcess:function(json){myApp.hidePreloader();console.log(json)},
error:function(error){myApp.hidePreloader()}});var maxWaiting=24E3;var changingPrompt=1E4;var refreshRate=1E3;var waiting=true;checkResponseJSON();function checkResponseJSON(){console.log("hehe");if(waiting){if(responseObject.readyState==4||responseObject.status==200){document.getElementById("post-title-input").value=responseObject.responseJSON.title;myApp.hidePreloader();waiting=false}setTimeout(function(){checkResponseJSON()},refreshRate)}}setTimeout(function(){if(waiting){waiting=false;myApp.hidePreloader();
myApp.alert("\u81e3\u59be\u8bfb\u4e0d\u51fa\u6765\u6807\u9898\u554a666666")}},maxWaiting);setTimeout(function(){if(waiting){myApp.hidePreloader();myApp.showPreloader("\u52aa\u529b\u52a0\u8f7d\u4e2d666666")}},changingPrompt)}
function postLinkByDeviceToken(){if(localStorage.usertoken==null||localStorage.usertoken=="null"){myApp.alert("\u8bf7\u60a8\u5148\u6ce8\u518c\uff01");return}var url=document.getElementById("post-address-input").value;var title=document.getElementById("post-title-input").value;var ut=localStorage.usertoken;var postGetUrl="http://meiliuer.com/api/create?name="+encodeURIComponent(title)+"&type=1&link="+encodeURIComponent(url)+"&device_token="+device_token+"&device_type=iOS";responseObject=$.ajax({url:postGetUrl,
type:"POST",dataType:"jsonp"})}
function validateUrl(value){return/^(?:(?:(?:https?|ftp):)?\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})).?)(?::\d{2,5})?(?:[/?#]\S*)?$/i.test(value)}
function postLink(){if(localStorage.usertoken==null||localStorage.usertoken=="null"){myApp.alert("\u8bf7\u60a8\u5148\u6ce8\u518c\uff01");return}var url=document.getElementById("post-address-input").value;var title=document.getElementById("post-title-input").value;if(!/\S/.test(url)){myApp.alert("\u5730\u5740\u680f\u4e0d\u80fd\u4e3a\u7a7a");return}if(!/\S/.test(title)){myApp.alert("\u6807\u9898\u680f\u4e0d\u80fd\u4e3a\u7a7a");return}if(!validateUrl(url)){myApp.alert("\u8bf7\u8f93\u5165\u771f\u5b9e\u6709\u6548\u7684\u7f51\u9875\u5730\u5740");
return}var ut=localStorage.usertoken;myApp.showIndicator();var postGetUrl="http://meiliuer.com/api/create?token="+ut+"&"+"name="+encodeURIComponent(title)+"&type=1&link="+encodeURIComponent(url)+"&callback=1&encoded=1";console.log(encodeURIComponent(url));$.ajax({url:postGetUrl,type:"POST",dataType:"jsonp",success:function(json){myApp.hideIndicator();console.log(json);getThumbPic(json.success);myApp.alert("\u592a6\u4e86\uff01\u53d1\u9001\u6210\u529f",function(){myApp.closeModal(".popup-post");updateListDataFromServer()})},
timeout:3E4,error:function(json){myApp.hideIndicator();myApp.alert("\u7f51\u7edc\u5f02\u5e38\uff0c\u4e00\u4f1a\u513f\u518d\u8bd5\u8bd5\uff1f")}})}function getPersonalInfo(){var ut=localStorage.usertoken;var postGetUrl="http://meiliuer.com/api/GetOwnInfo?token="+ut;$.ajax({url:postGetUrl,type:"GET",dataType:"jsonp",success:function(json){console.log(json)}})}
function signUp(){try{Keyboard.hide()}catch(err$4){}var email=document.getElementById("signup-email-input").value;var password=document.getElementById("signup-password-input").value;var username=document.getElementById("signup-username-input").value;var ajaxUrl="http://meiliuer.com/api/signup?udid="+udid+"&username="+username+"&email="+email+"&password="+password;myApp.showIndicator();$.ajax({url:ajaxUrl,type:"GET",dataType:"jsonp",success:function(json){myApp.hideIndicator();console.log(json);if(json.token!=
null){localStorage.usertoken=json.token;localStorage.user_id=json.user_id;localStorage.usernickname=json.username;localStorage.userId=json.user_id;loginPopupClose();loginStatusUpdate()}else if(json[0].email!=null)myApp.alert(json[0].email[0]);else if(json[0].password!=null)myApp.alert(json[0].password[0]);else if(json[0].username!=null)myApp.alert(json[0].username[0])},error:function(json){myApp.hideIndicator()}})}
function logIn(){try{Keyboard.hide()}catch(err$5){}myApp.showIndicator();var username=document.getElementById("post-email-input").value;var password=document.getElementById("post-password-input").value;var postGetUrl="http://meiliuer.com/api/login?udid="+udid+"&username="+username+"&password="+password+"&device_token="+device_token+"&device_type=iOS";$.ajax({url:postGetUrl,type:"GET",dataType:"jsonp",success:function(json){myApp.hideIndicator();if(json.token!=null){localStorage.usertoken=json.token;
localStorage.user_id=json.user_id;localStorage.usernickname=json.username;localStorage.userId=json.user_id;loginPopupClose();loginStatusUpdate();getUnreadNum()}else myApp.alert(json.error)},error:function(err){myApp.hideIndicator()}})}function addPostPopupOpen(){document.getElementById("post-address-input").value="";document.getElementById("post-title-input").value="";myApp.popup(".popup-post")}
function addTextPopupOpen(){document.getElementById("post-text-input").value="";myApp.popup(".popup-post-text")}function pastFromClipBoard(){cordova.plugins.clipboard.paste(function(text){document.getElementById("post-address-input").value=text})}
function logOut(){myApp.confirm("\u60a8\u786e\u5b9a\u8981\u767b\u51fa\u5417\uff1f",function(){localStorage.usertoken=null;configPopupClose();loginStatusUpdate();document.getElementById("post-password-input").value="";document.getElementById("signup-username-input").value="";document.getElementById("signup-email-input").value="";document.getElementById("signup-password-input").value=""})}function addPostPopupClose(){myApp.closeModal(".popup-post")}
function loginPopupClose(){myApp.closeModal(".popup-login");try{}catch(err$6){}}$(function(){$(".login-signup-input").focus(function(){$(".login-background").css("display","none")});$(".login-signup-input").blur(function(){console.log(12);$(".login-background").css("display","block")})});
function loginPopupOpen(){myApp.closeModal(".popup-tutorial");localStorage.hasShownTutorial="1";setTimeout(function(){myApp.popup(".popup-login")},100);try{Keyboard.hideFormAccessoryBar(false);StatusBar.backgroundColorByHexString("#ffffff")}catch(err$7){}document.getElementById("signup-username-input").onkeypress=function(e){if(e.keyCode==13)document.getElementById("signup-email-input").focus()};document.getElementById("signup-email-input").onkeypress=function(e){if(e.keyCode==13)document.getElementById("signup-password-input").focus()};
document.getElementById("signup-password-input").onkeypress=function(e){if(e.keyCode==13)signUp()};document.getElementById("post-email-input").onkeypress=function(e){if(e.keyCode==13)document.getElementById("post-password-input").focus()};document.getElementById("post-password-input").onkeypress=function(e){if(e.keyCode==13)logIn()}}function tutorialPopupOpen(){try{StatusBar.backgroundColorByHexString("#FFFFFF")}catch(err$8){}setTimeout(function(){myApp.popup(".popup-tutorial")},10)}
function loginStatusUpdate(){if(localStorage.hasShownTutorial=="1")if(!(localStorage.usertoken=="null"||localStorage.usertoken==null)){$(".login-only").css("display","block");$(".guest-only").css("display","none");try{StatusBar.backgroundColorByHexString("#f7f7f7")}catch(err$5){}mainView.router.load({pageName:"index"});updateListDataFromServer()}else{$(".login-only").css("display","none");$(".guest-only").css("display","block");setTimeout(function(){loginPopupOpen()},10)}else setTimeout(function(){tutorialPopupOpen();
setTimeout(function(){guestSwiper=myApp.swiper(".swiper-container",{onReachEnd:function(haha){setTimeout(function(){$("#tutorial-button").css("display","block");$("#tutorial-button").addClass("animated bounceIn")},400)}})},400)},10)}
$$(".infinite-scroll").on("infinite",function(){var fakeWaitingTime=300;if(mainView.url=="#user"){if(userLoading)return;$(".infinite-scroll-preloader").css("display","block");userLoading=true;userCurrentIndex++;setTimeout(function(){var urlPost="http://meiliuer.com/api/user?token="+localStorage.usertoken+"&user_id="+targetUserId+"&page="+userCurrentIndex;$.ajax({url:urlPost,type:"GET",dataType:"jsonp",success:function(json){hasClickedGetUserPost=false;if(json.length>0){userPostList=userPostList.concat(json);
workingList=userPostList;updateListHTMLFromListData(userPostList,"user-post-list");userLoading=false;$(".infinite-scroll-preloader ").css("display","none");document.getElementById("user-page-nav-title").innerHTML=workingList[0].username}else{userLoading=true;$(".infinite-scroll-preloader").css("display","none")}}})},fakeWaitingTime)}else if(mainView.url=="#index"&&mainPostPageTab=="hot"){if(homeLoading)return;$(".infinite-scroll-preloader").css("display","block");homeLoading=true;currentIndex++;setTimeout(function(){var postGetUrl=
"http://meiliuer.com/api/weeklyindex?udid="+udid+"&page="+currentIndex+"&token="+localStorage.usertoken+"&device_token="+device_token+"device_type=iOS";responseObject=$.ajax({url:postGetUrl,type:"GET",dataType:"jsonp",success:function(json){if(json.length>0){postList=postList.concat(json);workingList=postList;updateListHTMLFromListData(postList,"post-list");homeLoading=false;$(".infinite-scroll-preloader").css("display","none")}else{homeLoading=true;$(".infinite-scroll-preloader").css("display","none")}}})},
fakeWaitingTime)}else if(mainView.url=="#index"&&mainPostPageTab=="new"){if(homeLoading)return;$(".infinite-scroll-preloader").css("display","block");homeLoading=true;newCurrentIndex++;setTimeout(function(){var postGetUrl="http://meiliuer.com/api/index?udid="+udid+"&page="+newCurrentIndex+"&token="+localStorage.usertoken+"&device_token="+device_token+"device_type=iOS";responseObject=$.ajax({url:postGetUrl,type:"GET",dataType:"jsonp",success:function(json){if(json.length>0){newPostList=newPostList.concat(json);
workingList=newPostList;updateListHTMLFromListData(newPostList,"new-post-list");homeLoading=false;$(".infinite-scroll-preloader").css("display","none")}else{homeLoading=true;$(".infinite-scroll-preloader").css("display","none")}}})},fakeWaitingTime)}});var hasClickedGetUserPost;var targetUserId;function getHomePage(){mainView.router.loadPage({pageName:"index",animatePages:false})}
function loadCarmaNumber(){var lastCarma=document.getElementById("carma-number").innerHTML||-1;var urlPostUserData="http://meiliuer.com/api/getuserdata?user_id="+localStorage.userId;$.ajax({url:urlPostUserData,dataType:"jsonp",type:"GET",success:function(json){var carma=json.total_posts*5+json.total_ups_sent*1+json.total_ups_received_posts*2;if(lastCarma!=carma){console.log(carma);$("#carma-number").addClass("odometer");document.getElementById("carma-number").innerHTML=carma}console.log(json)}})}
function getUserPost(userId,selfPage){stopBubbling(this.event);mainView.router.loadPage({pageName:"user",animatePages:false});userCurrentIndex=1;var thisUsername="";if(selfPage)document.getElementById("logout-placeholder").innerHTML="<span onclick='logOut()'>\u767b\u51fa</span>";else document.getElementById("logout-placeholder").innerHTML="";hasClickedGetUserPost=true;targetUserId=userId;userLoading=false;var urlPost="http://meiliuer.com/api/user?token="+localStorage.usertoken+"&user_id="+userId+
"&page="+userCurrentIndex;document.getElementById("user-post-list").innerHTML="<div class='post-page-no-comment-placeholder'>\u6b63\u5728\u52a0\u8f7d...</div>";$.ajax({url:urlPost,dataType:"jsonp",success:function(json){hasClickedGetUserPost=false;userPostList=json;workingList=userPostList;console.log(json);if(json.length>0){document.getElementById("user-page-nav-title").innerHTML=json[0].username;updateListHTMLFromListData(json,"user-post-list")}else{if(selfPage)thisUsername=localStorage.usernickname;
else thisUsername="";document.getElementById("user-page-nav-title").innerHTML=thisUsername;updateListHTMLFromListData(json,"user-post-list","\u7528\u6237\u8fd8\u6ca1\u6709\u53d1\u8a00")}}});document.getElementById("number-of-posts").innerHTML=" - ";document.getElementById("number-of-likes-sent").innerHTML=" - ";document.getElementById("number-of-likes-received").innerHTML=" - ";var urlPostUserData="http://meiliuer.com/api/getuserdata?user_id="+userId;$.ajax({url:urlPostUserData,dataType:"jsonp",type:"GET",
success:function(json){document.getElementById("number-of-posts").innerHTML=json.total_posts;document.getElementById("number-of-likes-sent").innerHTML=json.total_ups_sent;document.getElementById("number-of-likes-received").innerHTML=json.total_ups_received_posts;console.log(json)}})};